using Microsoft.EntityFrameworkCore;

namespace dorks_and_dice_site.Services.Content.Storage;

internal static class ContentStorageSchema
{
    public static async Task EnsureCurrentAsync(
        ContentDbContext context,
        CancellationToken cancellationToken = default)
    {
        if (await context.Database.EnsureCreatedAsync(cancellationToken))
        {
            return;
        }

        if (context.Database.IsSqlite())
        {
            if (!await HasCurrentMediaSchemaAsync(context, SqliteSchemaCheck, cancellationToken))
            {
                await context.Database.ExecuteSqlRawAsync(SqliteContentAssetSchema, cancellationToken);
            }
            return;
        }

        if (context.Database.IsNpgsql())
        {
            if (!await HasCurrentMediaSchemaAsync(context, PostgresSchemaCheck, cancellationToken))
            {
                await context.Database.ExecuteSqlRawAsync(PostgresContentAssetSchema, cancellationToken);
            }
            return;
        }

        throw new NotSupportedException(
            $"Content database provider '{context.Database.ProviderName}' is not supported by the schema initializer.");
    }

    private static async Task<bool> HasCurrentMediaSchemaAsync(
        ContentDbContext context,
        string sql,
        CancellationToken cancellationToken)
    {
        var connection = context.Database.GetDbConnection();
        var closeWhenFinished = connection.State != System.Data.ConnectionState.Open;
        if (closeWhenFinished)
        {
            await context.Database.OpenConnectionAsync(cancellationToken);
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = sql;
            var count = Convert.ToInt32(await command.ExecuteScalarAsync(cancellationToken));
            return count == 3;
        }
        finally
        {
            if (closeWhenFinished)
            {
                await context.Database.CloseConnectionAsync();
            }
        }
    }

    private const string SqliteSchemaCheck = """
        SELECT COUNT(*)
        FROM sqlite_master
        WHERE (type = 'table' AND name = 'content_asset')
           OR (type = 'index' AND name IN (
               'IX_content_asset_asset_key',
               'IX_content_asset_asset_page_id_asset_sha256'))
        """;

    private const string PostgresSchemaCheck = """
        SELECT COUNT(*)
        FROM pg_class AS object
        INNER JOIN pg_namespace AS schema ON schema.oid = object.relnamespace
        WHERE schema.nspname = current_schema()
          AND object.relname IN (
              'content_asset',
              'IX_content_asset_asset_key',
              'IX_content_asset_asset_page_id_asset_sha256')
        """;

    private const string SqliteContentAssetSchema = """
        CREATE TABLE IF NOT EXISTS content_asset (
            asset_id INTEGER NOT NULL CONSTRAINT PK_content_asset PRIMARY KEY AUTOINCREMENT,
            asset_key TEXT NOT NULL,
            asset_page_id INTEGER NOT NULL,
            asset_file_name TEXT NOT NULL,
            asset_media_type TEXT NOT NULL,
            asset_length INTEGER NOT NULL,
            asset_sha256 TEXT NOT NULL,
            asset_created_utc TEXT NOT NULL,
            asset_data BLOB NOT NULL,
            CONSTRAINT FK_content_asset_content_page_asset_page_id
                FOREIGN KEY (asset_page_id) REFERENCES content_page (page_id) ON DELETE CASCADE
        );
        CREATE UNIQUE INDEX IF NOT EXISTS IX_content_asset_asset_key
            ON content_asset (asset_key);
        CREATE UNIQUE INDEX IF NOT EXISTS IX_content_asset_asset_page_id_asset_sha256
            ON content_asset (asset_page_id, asset_sha256);
        """;

    private const string PostgresContentAssetSchema = """
        CREATE TABLE IF NOT EXISTS content_asset (
            asset_id bigint GENERATED BY DEFAULT AS IDENTITY,
            asset_key text NOT NULL,
            asset_page_id bigint NOT NULL,
            asset_file_name text NOT NULL,
            asset_media_type text NOT NULL,
            asset_length bigint NOT NULL,
            asset_sha256 text NOT NULL,
            asset_created_utc timestamp with time zone NOT NULL,
            asset_data bytea NOT NULL,
            CONSTRAINT "PK_content_asset" PRIMARY KEY (asset_id),
            CONSTRAINT "FK_content_asset_content_page_asset_page_id"
                FOREIGN KEY (asset_page_id) REFERENCES content_page (page_id) ON DELETE CASCADE
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_content_asset_asset_key"
            ON content_asset (asset_key);
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_content_asset_asset_page_id_asset_sha256"
            ON content_asset (asset_page_id, asset_sha256);
        """;
}
