using Microsoft.EntityFrameworkCore;

namespace dorks_and_dice_site.Services.Content.Storage;

internal static class ContentStorageSchema
{
    public static async Task EnsureCurrentAsync(
        ContentDbContext context,
        CancellationToken cancellationToken = default)
    {
        if (!await context.Database.EnsureCreatedAsync(cancellationToken))
        {
            if (context.Database.IsSqlite())
            {
                if (!await HasTableAsync(context, "content_page_asset", cancellationToken))
                {
                    await context.Database.ExecuteSqlRawAsync(
                        SqliteCreateMediaSchema,
                        cancellationToken);
                }
            }
            else if (context.Database.IsNpgsql())
            {
                await context.Database.ExecuteSqlRawAsync(PostgresEnsureMediaSchema, cancellationToken);
            }
            else
            {
                throw new NotSupportedException(
                    $"Content database provider '{context.Database.ProviderName}' is not supported by the schema initializer.");
            }
        }

        await context.Database.ExecuteSqlRawAsync(
            context.Database.IsSqlite() ? SqliteCreateDependencySchema : PostgresCreateDependencySchema,
            cancellationToken);
        await context.Database.ExecuteSqlRawAsync(
            context.Database.IsSqlite() ? SqliteCreateRedirectSchema : PostgresCreateRedirectSchema,
            cancellationToken);
        await context.Database.ExecuteSqlRawAsync(
            context.Database.IsSqlite() ? SqliteCreateToolRegistrySchema : PostgresCreateToolRegistrySchema,
            cancellationToken);
    }

    private static async Task<bool> HasTableAsync(
        ContentDbContext context,
        string tableName,
        CancellationToken cancellationToken)
    {
        var connection = context.Database.GetDbConnection();
        var close = connection.State != System.Data.ConnectionState.Open;
        if (close) await context.Database.OpenConnectionAsync(cancellationToken);
        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=$name";
            var parameter = command.CreateParameter();
            parameter.ParameterName = "$name";
            parameter.Value = tableName;
            command.Parameters.Add(parameter);
            return Convert.ToInt32(await command.ExecuteScalarAsync(cancellationToken)) == 1;
        }
        finally
        {
            if (close) await context.Database.CloseConnectionAsync();
        }
    }

    private const string SqliteCreateMediaSchema = """
        CREATE TABLE IF NOT EXISTS content_asset (
            asset_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            asset_key TEXT NOT NULL, asset_file_name TEXT NOT NULL,
            asset_media_type TEXT NOT NULL, asset_length INTEGER NOT NULL,
            asset_sha256 TEXT NOT NULL, asset_created_utc TEXT NOT NULL, asset_data BLOB NOT NULL);
        CREATE UNIQUE INDEX IF NOT EXISTS IX_content_asset_asset_key ON content_asset(asset_key);
        CREATE INDEX IF NOT EXISTS IX_content_asset_asset_sha256 ON content_asset(asset_sha256);
        CREATE TABLE IF NOT EXISTS content_page_asset (
            page_id INTEGER NOT NULL, asset_id INTEGER NOT NULL, relationship TEXT NOT NULL,
            PRIMARY KEY(page_id, asset_id),
            FOREIGN KEY(page_id) REFERENCES content_page(page_id) ON DELETE CASCADE,
            FOREIGN KEY(asset_id) REFERENCES content_asset(asset_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS IX_content_page_asset_asset_id ON content_page_asset(asset_id);
        CREATE TABLE IF NOT EXISTS content_revision_asset (
            revision_id INTEGER NOT NULL, asset_key TEXT NOT NULL, relationship TEXT NOT NULL,
            PRIMARY KEY(revision_id, asset_key),
            FOREIGN KEY(revision_id) REFERENCES content_revision(revision_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS IX_content_revision_asset_asset_key ON content_revision_asset(asset_key);
        """;

    private const string SqliteCreateDependencySchema = """
        CREATE TABLE IF NOT EXISTS content_page_asset_dependency (
            page_id INTEGER NOT NULL, asset_source_key TEXT NOT NULL, asset_key TEXT NOT NULL,
            PRIMARY KEY(page_id, asset_source_key, asset_key),
            FOREIGN KEY(page_id) REFERENCES content_page(page_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS IX_content_page_asset_dependency_asset_key
            ON content_page_asset_dependency(asset_key);
        """;

    private const string PostgresEnsureMediaSchema = """
        CREATE TABLE IF NOT EXISTS content_asset (
            asset_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            asset_key text NOT NULL, asset_file_name text NOT NULL, asset_media_type text NOT NULL,
            asset_length bigint NOT NULL, asset_sha256 text NOT NULL,
            asset_created_utc timestamp with time zone NOT NULL, asset_data bytea NOT NULL);
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_content_asset_asset_key" ON content_asset(asset_key);
        CREATE INDEX IF NOT EXISTS "IX_content_asset_asset_sha256" ON content_asset(asset_sha256);
        CREATE TABLE IF NOT EXISTS content_page_asset (
            page_id bigint NOT NULL, asset_id bigint NOT NULL, relationship text NOT NULL,
            PRIMARY KEY(page_id,asset_id),
            FOREIGN KEY(page_id) REFERENCES content_page(page_id) ON DELETE CASCADE,
            FOREIGN KEY(asset_id) REFERENCES content_asset(asset_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS "IX_content_page_asset_asset_id" ON content_page_asset(asset_id);
        CREATE TABLE IF NOT EXISTS content_revision_asset (
            revision_id bigint NOT NULL, asset_key text NOT NULL, relationship text NOT NULL,
            PRIMARY KEY(revision_id,asset_key),
            FOREIGN KEY(revision_id) REFERENCES content_revision(revision_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS "IX_content_revision_asset_asset_key" ON content_revision_asset(asset_key);
        """;

    private const string PostgresCreateDependencySchema = """
        CREATE TABLE IF NOT EXISTS content_page_asset_dependency (
            page_id bigint NOT NULL, asset_source_key text NOT NULL, asset_key text NOT NULL,
            PRIMARY KEY(page_id, asset_source_key, asset_key),
            FOREIGN KEY(page_id) REFERENCES content_page(page_id) ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS "IX_content_page_asset_dependency_asset_key"
            ON content_page_asset_dependency(asset_key);
        """;

    private const string SqliteCreateRedirectSchema = """
        CREATE TABLE IF NOT EXISTS content_redirect (
            redirect_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            redirect_namespace TEXT NOT NULL,
            redirect_slug TEXT NOT NULL,
            redirect_page_id INTEGER NOT NULL,
            redirect_created_utc TEXT NOT NULL,
            FOREIGN KEY(redirect_page_id) REFERENCES content_page(page_id) ON DELETE CASCADE);
        CREATE UNIQUE INDEX IF NOT EXISTS IX_content_redirect_redirect_namespace_redirect_slug
            ON content_redirect(redirect_namespace, redirect_slug);
        CREATE INDEX IF NOT EXISTS IX_content_redirect_redirect_page_id
            ON content_redirect(redirect_page_id);
        """;

    private const string PostgresCreateRedirectSchema = """
        CREATE TABLE IF NOT EXISTS content_redirect (
            redirect_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            redirect_namespace text NOT NULL,
            redirect_slug text NOT NULL,
            redirect_page_id bigint NOT NULL,
            redirect_created_utc timestamp with time zone NOT NULL,
            FOREIGN KEY(redirect_page_id) REFERENCES content_page(page_id) ON DELETE CASCADE);
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_content_redirect_redirect_namespace_redirect_slug"
            ON content_redirect(redirect_namespace, redirect_slug);
        CREATE INDEX IF NOT EXISTS "IX_content_redirect_redirect_page_id"
            ON content_redirect(redirect_page_id);
        """;

    private const string SqliteCreateToolRegistrySchema = """
        CREATE TABLE IF NOT EXISTS tool_registration (
            tool_id TEXT NOT NULL PRIMARY KEY,
            tool_slug TEXT NOT NULL,
            tool_display_name TEXT NOT NULL,
            tool_description TEXT NULL,
            tool_integration_type INTEGER NOT NULL DEFAULT 0,
            tool_upstream_base_url TEXT NULL,
            tool_frontend_entry_point TEXT NULL,
            tool_health_path TEXT NULL,
            tool_modes TEXT NOT NULL DEFAULT '[]',
            tool_allow_anonymous INTEGER NOT NULL DEFAULT 1,
            tool_enabled INTEGER NOT NULL DEFAULT 0,
            tool_created_at TEXT NOT NULL,
            tool_updated_at TEXT NOT NULL,
            CONSTRAINT ck_tool_registration_integration_type
                CHECK (tool_integration_type IN (0, 1)),
            CONSTRAINT ck_tool_registration_slug_not_empty
                CHECK (length(trim(tool_slug)) > 0),
            CONSTRAINT ck_tool_registration_display_name_not_empty
                CHECK (length(trim(tool_display_name)) > 0));
        CREATE UNIQUE INDEX IF NOT EXISTS ux_tool_registration_slug_ci
            ON tool_registration(lower(tool_slug));
        """;

    private const string PostgresCreateToolRegistrySchema = """
        CREATE TABLE IF NOT EXISTS tool_registration (
            tool_id uuid NOT NULL,
            tool_slug text NOT NULL,
            tool_display_name text NOT NULL,
            tool_description text NULL,
            tool_integration_type smallint NOT NULL DEFAULT 0,
            tool_upstream_base_url text NULL,
            tool_frontend_entry_point text NULL,
            tool_health_path text NULL,
            tool_modes text[] NOT NULL DEFAULT ARRAY[]::text[],
            tool_allow_anonymous boolean NOT NULL DEFAULT true,
            tool_enabled boolean NOT NULL DEFAULT false,
            tool_created_at timestamp with time zone NOT NULL,
            tool_updated_at timestamp with time zone NOT NULL,
            CONSTRAINT pk_tool_registration PRIMARY KEY (tool_id),
            CONSTRAINT ck_tool_registration_integration_type
                CHECK (tool_integration_type IN (0, 1)),
            CONSTRAINT ck_tool_registration_slug_not_empty
                CHECK (length(btrim(tool_slug)) > 0),
            CONSTRAINT ck_tool_registration_display_name_not_empty
                CHECK (length(btrim(tool_display_name)) > 0));
        CREATE UNIQUE INDEX IF NOT EXISTS ux_tool_registration_slug_ci
            ON tool_registration(lower(tool_slug));
        """;
}
